powershell -Command "Invoke-WebRequest https://coderbag.com/assets/downloads/cpm/currentversion/QuickCpuSetup64.zip -OutFile QuickCpuSetup64.zip"
powershell -Command "Invoke-WebRequest https://download2266.mediafire.com/fmk43ym5410g/ewpy1p0rr132thk/MSI_util_v3.zip -OutFile MSI_util_v3.zip"
powershell -Command "Invoke-WebRequest https://www.speedguide.net/files/TCPOptimizer.exe -OutFile TCPOptimizer.exe"
powershell -Command "Invoke-WebRequest 'https://www.wagnardsoft.com/DDU/download/DDU v18.0.3.5.exe' -OutFile 'DDU v18.0.3.5.exe'"
powershell -Command "Invoke-WebRequest 'https://www.wagnardsoft.com/ISLC/ISLC v1.0.2.2.exe' -OutFile 'ISLC v1.0.2.2.exe'"